# Generated by Django 3.0.5 on 2023-04-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='profile_pic',
        ),
    ]
